import { PhysicalConstant } from "../types";

export const MANDATORY_CONSTANTS: PhysicalConstant[] = [
  {
    symbol: "h",
    latex: "h",
    name: "Planck's Constant",
    valueSI: "6.63 \\times 10^{-34}",
    valueAtomic: "4.136 \\times 10^{-15}",
    units: "\\text{J}\\cdot\\text{s} \\text{ or } \\text{eV}\\cdot\\text{s}",
    notes: "Fundamental quantum of action; governs energy quantization E = hf.",
  },
  {
    symbol: "hbar",
    latex: "\\hbar = \\frac{h}{2\\pi}",
    name: "Reduced Planck Constant (Dirac's Constant)",
    valueSI: "1.05 \\times 10^{-34}",
    valueAtomic: "6.582 \\times 10^{-16}",
    units: "\\text{J}\\cdot\\text{s} \\text{ or } \\text{eV}\\cdot\\text{s}",
    notes: "Appears in Schrödinger's equation, orbital angular momentum L = n\\hbar, and uncertainty bounds.",
  },
  {
    symbol: "c",
    latex: "c",
    name: "Speed of Light in Vacuum",
    valueSI: "3.00 \\times 10^{8}",
    units: "\\text{m/s}",
    notes: "Universal relativistic invariant speed; maximum speed of causality.",
  },
  {
    symbol: "e",
    latex: "e",
    name: "Elementary Electric Charge",
    valueSI: "1.60 \\times 10^{-19}",
    units: "\\text{C}",
    notes: "Fundamental charge of proton (+e) and electron (-e). 1 eV = 1.60 \\times 10^{-19} J.",
  },
  {
    symbol: "m_e",
    latex: "m_e = m_0",
    name: "Electron Rest Mass",
    valueSI: "9.11 \\times 10^{-31}",
    valueAtomic: "0.511",
    units: "\\text{kg} \\text{ (or } 0.511\\text{ MeV/}c^2\\text{)}",
    notes: "Rest mass used in de Broglie waves, Bohr orbital dynamics, and Compton recoil.",
  },
  {
    symbol: "R_H",
    latex: "R_H",
    name: "Rydberg Constant (Hydrogen)",
    valueSI: "1.097 \\times 10^{7}",
    units: "\\text{m}^{-1}",
    notes: "Determines spectral wavelengths in 1/\\lambda = R_H(1/n_f^2 - 1/n_i^2).",
  },
  {
    symbol: "sigma",
    latex: "\\sigma",
    name: "Stefan-Boltzmann Constant",
    valueSI: "5.67 \\times 10^{-8}",
    units: "\\text{W}\\cdot\\text{m}^{-2}\\cdot\\text{K}^{-4}",
    notes: "Total blackbody emissive power P = \\sigma A \\epsilon T^4.",
  },
  {
    symbol: "k_B",
    latex: "k_B",
    name: "Boltzmann Constant",
    valueSI: "1.38 \\times 10^{-23}",
    valueAtomic: "8.617 \\times 10^{-5}",
    units: "\\text{J/K} \\text{ or } \\text{eV/K}",
    notes: "Relates thermal energy to absolute temperature; classical equipartition energy k_B T.",
  },
  {
    symbol: "lambda_c",
    latex: "\\lambda_c = \\frac{h}{m_0 c}",
    name: "Compton Wavelength (Electron)",
    valueSI: "2.43 \\times 10^{-12}",
    valueAtomic: "0.0243",
    units: "\\text{m} = 2.43\\text{ pm} = 0.0243\\text{ \\AA}",
    notes: "Characteristic length scale for photon-electron elastic scattering; \\Delta\\lambda = \\lambda_c(1-\\cos\\theta).",
  },
  {
    symbol: "a_0",
    latex: "a_0 = \\frac{\\hbar^2}{m k e^2}",
    name: "Bohr Radius",
    valueSI: "0.529 \\times 10^{-10}",
    valueAtomic: "0.0529",
    units: "\\text{m} = 0.529\\text{ \\AA} \\approx 0.053\\text{ nm}",
    notes: "Radius of the n=1 ground state orbit of hydrogen atom.",
  },
  {
    symbol: "E_1",
    latex: "E_1",
    name: "Hydrogen Ground State Energy",
    valueSI: "-2.176 \\times 10^{-18}",
    valueAtomic: "-13.6",
    units: "\\text{eV} \\text{ or } \\text{J}",
    notes: "Ground state binding energy of electron in hydrogen. Ionization energy is +13.6 eV.",
  },
];

export const CONSTANTS = {
  h: 6.62607e-34,
  hbar: 1.05457e-34,
  c: 2.99792e8,
  e: 1.60218e-19,
  m_e: 9.10938e-31,
  m_p: 1.67262e-27,
  k_B: 1.38065e-23,
  sigma: 5.67037e-8,
  R_H: 1.09737e7,
  lambda_c: 2.42631e-12,
  a_0: 5.29177e-11,
  E_1_eV: -13.606,
};
